global using OptRes;
global using static OptRes.Ext;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Data;
global using System.Diagnostics;
global using System.Linq;
global using MathProg;
global using static MathProg.Extensions;
